#DataSource
spring:
  # redis
  redis:
    database: 12
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 43200000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000

  datasource:
    ##MySql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/web-db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root

    #DataSource type
    druid:
      #连接初始值，连接池启动时创建的连接数量的初始值
      initialSize: 5
      #最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止 ，0时无限制
      minIdle: 5
      #连接池的最大值，同一时间可以从池分配的最多连接数量，0时无限制
      maxActive: 20
      #配置获取连接等待超时的时间(毫秒)
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      # 打开PSCache，指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
      filters: stat, wall
      # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        allow: 127.0.0.1


mybatis-plus:
  # mp.baomidou.com
  # 在使用 mybatis-plus 时，如果你是简单的增删改查
  # Mapper 继承该接口后，无需编写 mapper.xml 映射文件，即可获得CRUD功能。
  # 想写你就写
  # lombok
  mapper-locations: classpath:/mybatis-mappers/*/*Dao.xml
  typeAliasesPackage: com.mer.pojo
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 t_
    #    table-prefix: t_
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false


# LOGGING
logging:
  config: classpath:log/logback-spring.xml

knife4j:
  #是否开启Knife4j增强模式
  enable: true
  # 开启生产环境屏蔽
  production: false
  setting:
    #显示OpenAPI规范
    enableOpenApi: false
    #调试Tab是否显示AfterScript功能,默认开启
    enableAfterScript: false
    #Ui默认显示语言,目前主要有两种:中文(zh-CN)、英文(en-US)
    language: zh-CN
    #是否显示界面中SwaggerModel功能
    enableSwaggerModels: true
    #重命名SwaggerModel名称,默认
    swaggerModelName: ModelVo
    enableHost: true